[tool.poetry]
name = "exercise1"
version = "0.1.0"
description = ""
authors = ["Lukas <lukas.mah@outlook.at>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.*"
mrjob = "^0.7.4"
pytest = "^8.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
